#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 13 12:56:33 2020
Dictionary of variables measured at Cape Verde Observtory and relevent 
information for dataset access, processing and plotting. 
@author: mjr583
"""

CVAO_dict = {
     'O3' : {'species' : 'O3',   
                 'ceda_url' : 'http://dap.ceda.ac.uk/thredds/dodsC/badc/capeverde/data/cv-tei-o3/2019/ncas-tei-49i-1_cvao_20190101_o3-concentration_v1.nc',
                 'ebas_url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20061002000000.20190425081904.uv_abs.ozone.air.12y.1h.GB12L_CVO_Ozone_Thermo49series.GB12L_Thermo.lev2.nc',
                 'ebas_var_name' : 'ozone_nmol_per_mol_amean',
                 'ceda_var_name' : '',               
                 'longname' : 'ozone',
                 'abbr' : '$O_3$',
                 'unit': 'ppbv',
                 'scale' : '1e9',
                 'yscale' : 'linear',
                 'start_year' : '2006',
                 'merge_pref' : '',
                 'merge_suff' : '',
                 'instrument' : ''
                },
    'CO' : {'species' : 'CO',
                'ebas_url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20160101000000.20190425083930.online_crds.carbon_monoxide.air.3y.1h.GB12L_CVO_Picarro_G2401.GB12L_Picarro.lev2.nc',
                'ceda_url' : '',
                'ebas_var_name' : 'carbon_monoxide_amean',
                'ceda_var_name' : '',
                'longname' : 'carbon_monoxide',
                'abbr' : 'CO',
                'unit': 'ppbv',
                'scale' : '1e9',
                'yscale' : 'linear',
                'start_year' : '2006',
                'merge_pref' : '',
                'merge_suff' : ' (ppbV)',
                'instrument' : ''
                },
    'CH4' : {'species' : 'CH4',
                'ebas_url' : '',
                'ceda_url' : '',
                'ebas_var_name' : '',
                'ceda_var_name' : '',
                'longname' : 'methane',
                'abbr' : '$CH_4$',
                'unit': 'ppbv',
                'scale' : '1e9',
                'yscale' : 'linear',
                'start_year' : '2006',
                'merge_pref' : '',
                'merge_suff' : ' all (ppbV)',
                'instrument' : ''
                },
    'CO2' : {'species' : 'CO2',
                'ebas_url' : '',
                'ceda_url' : '',
                'ebas_var_name' : '',
                'ceda_var_name' : '',
                'longname' : 'carbon dioxide',
                'abbr' : '$CO_2$',
                'unit': 'ppmv',
                'scale' : '1e9',
                'yscale' : 'linear',
                'start_year' : '2006',
                'merge_pref' : '',
                'merge_suff' : ' (ppmV)',
                'instrument' : ''
                },
    'NO' : {'species' : 'NO',
                'ebas_url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20170101000000.20191024143042.chemiluminescence_photolytic..air.2y.1h.GB12L_CVO_AQD_Nox.GB12L_AQD_NOx.lev2.nc',
                'ceda_url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20170101000000.20191024143042.chemiluminescence_photolytic..air.2y.1h.GB12L_CVO_AQD_Nox.GB12L_AQD_NOx.lev2.nc',                
                'ebas_var_name' : 'nitrogen_monoxide_nmol_per_mol',
                'ceda_var_name' : '',                
                'longname' : 'nitrogen_monoxide',
                'abbr' : 'NO',
                'unit': 'pptv',
                'scale' : '1e9',
                'yscale' : 'log',
                'start_year' : '2006',
                'merge_pref' : '',
                'merge_suff' : ' (pptV)',
                'instrument' : ''
                },
    'NO2' : {'species' : 'NO2',
                 'ebas_url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20170101000000.20191024143042.chemiluminescence_photolytic..air.2y.1h.GB12L_CVO_AQD_Nox.GB12L_AQD_NOx.lev2.nc',
                 'ceda_url' : '',
                 'ebas_var_name' : 'nitrogen_dioxide_nmol_per_mol',
                 'ceda_var_name' : '',
                 'longname' : 'nitrogen_dioxide',
                 'abbr' : '$NO_2$',
                 'unit': 'pptv',
                 'scale' : '1e9',
                 'yscale' : 'linear',
                 'start_year' : '2006',
                 'merge_pref' : '',
                 'merge_suff' : ' (pptV)',
                 'instrument' : ''
                },
    'propane' : {'species' : 'propane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'propane',
                     'abbr' : '$C_3H_8$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'ethane' : {'species' : 'ethane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'ethane',
                     'abbr' : '$C_2H_6$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)'                     
                },
    'iso_butane' : {'species' : 'iso_butane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'isobutane',
                     'abbr' : '$HC(CH_3)_3$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (;pptV)',
                     'instrument' : ''
                },
    'n_butane' : {'species' : 'n_butane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'nbutane',
                     'abbr' : '$C_4H_{10}$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'acetylene' : {'species' : 'acetylene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'acetylene',
                     'abbr' : '$C_2H_2$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'iso_pentane' : {'species' : 'iso_pentane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'isopentane',
                     'abbr' : '$C_5H_{12}$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'n_pentane' : {'species' : 'n_pentane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'n_pentane',
                     'abbr' : '$C_5H_{12}$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'ethene' : {'species' : 'ethene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'ethene',
                     'abbr' : '$C_2H_4$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'propene' : {'species' : 'propene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'propene',
                     'abbr' : '$C_3H_6$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'benzene' : {'species' : 'benzene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'benzene',
                     'abbr' : '$C_6H_6$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'toluene' : {'species' : 'toluene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'toluene',
                     'abbr' : '$C_6H_5CH_3$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'Mercury' : {'species' : 'Mercury',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Mercury',
                     'abbr' : 'T.G. Hg',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : 'Total Gaseous ',
                     'merge_suff' : ' (ngm-3)',
                     'instrument' : ''
                },
    'CHBr3' : {'species' : 'CHBr3',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Bromoform',
                     'abbr' : '$CHBr_3$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'CH2Br2' : {'species' : 'CH2Br2',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Dibromomethane',
                     'abbr' : '$CH_2Br_2$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'CCl4' : {'species' : 'CCl4',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Carbon Tetrachloride',
                     'abbr' : '$CCl_4$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'CH2I2' : {'species' : 'CH2I2',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Diiodomethane',
                     'abbr' : '$CH_2I_2$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'CH3I' : {'species' : 'CH3I',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Methyl Iodide',
                     'abbr' : '$CH_3I$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'CH2ICl' : {'species' : 'CH2ICl',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Chloroiodomethane',
                     'abbr' : '$CH_2ICl$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'CHCl3' : {'species' : 'CHCl3',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Chloroform',
                     'abbr' : '$CHCl_3$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'CH2BrCl' : {'species' : 'CH2BrCl',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Bromochloromethane',
                     'abbr' : '$CH_2BrCl$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'CH2IBr' : {'species' : 'CH2IBr',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Bromoiodomethane',
                     'abbr' : '$CH_2IBr$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'CHBr2Cl' : {'species' : 'CHBr2Cl',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Dibromochloromethane',
                     'abbr' : '$CHBr_2Cl$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'SO2' : {'species' : 'SO2',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Sulphur dioxide',
                     'abbr' : '$SO_2$',
                     'unit': 'ppbv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (ppbV)',
                     'instrument' : ''
                },
    'DMS' : {'species' : 'DMS',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Dimethyl sulphide',
                     'abbr' : 'DMS',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log', # query
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'Isoprene' : {'species' : 'Isoprene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Isoprene',
                     'abbr' : 'Isoprene',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : ' (pptV)',
                     'instrument' : ''
                },
    'acetaldehyde' : {'species' : 'acetaldehyde',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Acetaldehyde',
                     'abbr' : '$C_2H_4O$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : '',
                     'instrument' : ''
                },
    'meoh' : {'species' : 'meoh',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Methanol',
                     'abbr' : '$CH_3OH$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : '',
                     'instrument' : ''
                },
    'acetone' : {'species' : 'acetone',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Acetone',
                     'abbr' : '$C_3H_6O$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_pref' : '',
                     'merge_suff' : '',
                     'instrument' : ''
                },
    }
'''
    'NOx' : {'url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20170101000000.20191024143042.chemiluminescence_photolytic..air.2y.1h.GB12L_CVO_AQD_Nox.GB12L_AQD_NOx.lev2.nc',
                'species' : 'NOx',
                'longname' : 'nitrogen_oxides',
                'abbr' : '$NO_x$',
                'unit': 'ppbv',
                'scale' : '1e9',
                'start_year' : '2006',
                'var_name_a' : 'nitrogen_monoxide_nmol_per_mol',
                'var_name_b' : 'nitrogen_dioxide_nmol_per_mol'
                },
     }
'''